// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwzKaBjVUO3D9B8YRQbNYN3kqXTY9RIOw',
    appId: '1:145715267443:web:1d8a431f9fdf840b9ba706',
    messagingSenderId: '145715267443',
    projectId: 'uoembu',
    authDomain: 'uoembu.firebaseapp.com',
    storageBucket: 'uoembu.appspot.com',
    measurementId: 'G-MBCW0NH2QB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8Zf1MPJPtsnhHPctxbiNCRV53GBrkfks',
    appId: '1:145715267443:android:0117f2db329d8e9b9ba706',
    messagingSenderId: '145715267443',
    projectId: 'uoembu',
    storageBucket: 'uoembu.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbodKFqz08fOIw92BNnRDEb0aSJA6DvUs',
    appId: '1:145715267443:ios:763dc4a09a4a97369ba706',
    messagingSenderId: '145715267443',
    projectId: 'uoembu',
    storageBucket: 'uoembu.appspot.com',
    iosBundleId: 'com.lxmwaniky.universityOfEmbu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbodKFqz08fOIw92BNnRDEb0aSJA6DvUs',
    appId: '1:145715267443:ios:9bd4392adc701c0d9ba706',
    messagingSenderId: '145715267443',
    projectId: 'uoembu',
    storageBucket: 'uoembu.appspot.com',
    iosBundleId: 'com.lxmwaniky.universityOfEmbu.RunnerTests',
  );
}
